file_min_updated_hours: 3
site:
  url: https://github.com/timschneeb/awesome-shizuku
  title: "Recent awesome-shizuku additions"
  description: |
    "This page tracks recent additions to the awesome-shizuku list on GitHub.
    
    Note: Modified entries are also considered new. Changes to existing items will be reflected here as well.
    "
sources:
  timschneeb/awesome-shizuku:
    category: Android
    files:
      README.md:
        index: true
        name: 'awesome-shizuku'
        options:
          type: list
          min_heading_level: 4
          #max_heading_level: 1
