file_min_updated_hours: 5
site:
  url: https://github.com/timschneeb/awesome-shizuku
  title: "Track Awesome Shizuku Apps"
  description: "
    This page tracks recent additions and changes to existing entries to the awesome-shizuku list on GitHub.

    
    "
    
sources:
  timschneeb/awesome-shizuku:
    category: Android
    files:
      README.md:
        index: true
        name: 'Awesome Shizuku Apps'
        options:
          type: list
          min_heading_level: 4
          #max_heading_level: 1
